name: Run tests and deploy

# Run this workflow whenever something new is pushed.
on: 
  push:
    branches: [ blog ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3        
        with:
          python-version: '3.10.8'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}          
          script: |                      
            cd farmblog
            echo ${{secrets.PASSWORD }} | sudo -S git switch blog       
            echo ${{secrets.PASSWORD }} | sudo -S git pull git@github.com:milodepilo/farm.git blog
            echo ${{secrets.PASSWORD }} | sudo -S python3 -m venv venv
            source venv/bin/activate
            echo ${{secrets.PASSWORD }} | sudo -S pip install farmblog-1.0.0-py3-none-any.whl
            echo ${{secrets.PASSWORD }} | sudo -S flask --app farmblog init-db
            echo ${{secrets.PASSWORD }} | sudo -S mkdir -p ~/farmblog/venv/var/farmblog-instance/
            echo ${{secrets.PASSWORD }} | ~/farmblog/venv/var/farmblog-instance/config.py
            echo ${{secrets.DEV_SECRET_KEY}} | ~/farmblog/venv/var/farmblog-instance/config.py
            echo ${{secrets.PASSWORD }} | sudo -S systemctl restart farm