name: Run tests and deploy

# Run this workflow whenever something new is pushed.
on: 
  push:
    branches: [ blog ]

jobs:  
  checkout-and-installing:
  name: checkout instal and pip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3        
        with:
          python-version: '3.10.8'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: install farmblog
        run: pip install -e . 
  testing:
  name: pytest
    needs: checkout-and-installing
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: pytest
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}  
          script: |
            cd farmblog                 
            echo ${{secrets.PASSWORD}} | sudo -S git pull git@github.com:milodepilo/farm.git blog
            echo ${{secrets.PASSWORD}} | sudo -S systemctl restart farmblog
         