name: Run tests

# Run this workflow whenever something new is pushed.
on: 
  push:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.10.8'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Deploy Farm app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} 
          key: ${{ secrets.SSH_KEY }}         
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{secrets.SSH_PHRASE}}
          

          script: |
            mkdir farm_app
            cd farm_app
            git clone git@github.com:milodepilo/farm.git
            echo "Deployment succesfull"